
# Capture token of real user from network - headers tab of API call

@business-fred-token 
@customer-karen-testtoken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InZKaTB5Z0FWd0ZhcnFCZk9sODAzLSJ9.eyJodHRwczovL3NhdmVmb3JwZXJrcy5jb20vdXNlcl90eXBlIjoiY3VzdG9tZXIiLCJpc3MiOiJodHRwczovL2Rldi1pc2RzbnpsNThwZ214M2t3LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2OThiMzlmMTYwZTY1NWZhOTI4ZTdhMmQiLCJhdWQiOlsiaHR0cHM6Ly9zYXZlZm9ycGVya3MuY29tIiwiaHR0cHM6Ly9kZXYtaXNkc256bDU4cGdteDNrdy51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzcxMjQ0OTkzLCJleHAiOjE3NzEzMzEzOTMsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiJJNHBubVdaUlVmeW9XRWd2SUpKS0JMYk56Z2xCS0VQQiIsInBlcm1pc3Npb25zIjpbXX0.N7Jpc1elX7HCCH7MIhj_g75V_txfyjX2pbK5xOA8GwIe-5uhHJBJmco5wsDsIntJoDtMv4BcWviNeTWtwo0XgoOfkq-MRd4IPvo-PJE4wbgamKFRXlRVx9xCs4gdTmO5eZLlyeQccTJG91MI8Cfap2yhNIFq-TMq32r5Ada_UsaatoRiTqBggpZk653MkcGEqQ0RJEQJGz0i_aukzzbTQcQIsgd0YTwlvO6Ez6KVFsnlEHWqTiRlR1h-8i49Kq9SQ3amDW-DV_rKTV2wIo4iHEp8mlRKb2sipWya9i7L0Esl0qSYAPOXFvBCnh6OFKHCo6wMKfceUqtITRf6UTyk5A
@url = http://localhost:5143/api/
@contentType = application/json

@auth0UserId = auth0|698b36c760e655fa928e76b8
@businessId = 75B8DDC5-5162-454D-A4CB-D945C00ED74B
@businessUserId = 46C48332-E633-43D7-BB4C-C66322F56535
@rewardId = f11a2397-e293-4ecf-bac7-ab8cf18d812d
@customerId = 3E2D99B8-3B81-4880-B151-FE6FA95600E6

# *************** HEALTH CHECK **************************

###
GET {{url}}health


# *************** ADMIN **************************

###
GET {{url}}admin/businesses


# *************** Business **************************

# Step 10 - Create a new business along with the first business user who will be set to admin.
###
POST {{url}}business
Content-Type: application/json

{
"BusinessName": "Joes coffee shop",
"BusinessDescription": "A nice coffee sop",
"BusinessCategoryId": "22222222-2222-2222-2222-222222222222",
"BusinessUserAuthProviderId": "auth01234",
"BusinessUserEmail": "joe@example.com",
"BusinessUserName": "Joe Admin"
}

# ***************** BusinessUser ***************************
# Step 20 - Get the Business details for a BusinessUser - DEPRECATED
###
GET {{url}}business-user/auth01234/businesses

# Reward Owner User - DEPRECATED
# Step 1: Get RewardOwnerUser by AuthProviderId
###
GET {{url}}business-user/by-auth/auth0|6978c6069f7c25664b0c13cf

# Use this instead
# Step 30 Get BusinessUser and Business details and see if Business.Name has been completed (BusinessProfileExists) 
### Combine above two into one call
GET {{url}}business-user/profile/{{auth0UserId}}

# END Reward Owner User



# Get Rewards for a businessId
# Step 30
###
GET {{url}}business/{{businessId}}/rewards
X-BusinessUser-Id: {{businessUserId}}

# Create a new Reward
###
POST {{url}}business/{{businessId}}/rewards
X-BusinessUser-Id: {{businessUserId}}
Content-Type: application/json

{
  "name": "Free Coffee",
  "rewardType": "IncrementalPoints",
  "costPoints": 10
}

# Update a reward
###
PUT {{url}}business/{{businessId}}/rewards/{{rewardId}}
Content-Type: application/json
X-BusinessUser-Id: {{businessUserId}}

{
  "name": "Buy 5 loaves and get 1 free (Updated)",
  "rewardType": "IncrementalPoints",
  "costPoints": 3,
  "isActive": true
}



# Business Category
###
GET {{url}}business-category


# Initial scan of qr code
###
GET {{url}}business/{{businessId}}/scans/{{rewardId}}/customerbalance/QR001-ALICE-9999


# 1 Expect current balance of 2
# Scan a users qr code to claim points for a reward and also reward redemption
###
POST {{url}}business/{{businessId}}/scans
X-BusinessUser-Id: {{businessUserId}}
Content-Type: application/json

{
  "RewardId": "ED83EB01-C41A-4AE7-8A41-D741C2F093E8",
  "QrCodeValue": "QR003-CHARLIE-BBBB", 
  "PointsChange": 4,
  "NumRewardsToClaim": 4
}



# Customer
###
GET {{url}}customer/by-auth/{{auth0UserId}}


# Create a new customer.
###
POST {{url}}customer
Content-Type: application/json

{
"AuthProviderId": "auth01237",
"Email": "customer@example.com",
"Name": "Joe Customer"
}

# Get dashboard info for a customer
###
GET {{url}}customer/{{customerId}}/dashboard
Authorization: Bearer  {{customer-karen-testtoken}}

# Delete a customer
###
DELETE {{url}}customer/{{customerId}}