// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TapForPerksAPI.DbContexts;

#nullable disable

namespace TapForPerksAPI.Migrations
{
    [DbContext(typeof(TapForPerksContext))]
    partial class TapForPerksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TapForPerksAPI.Entities.LoyaltyOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__loyalty___3213E83FEC734646");

                    b.ToTable("loyalty_owner", (string)null);
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.LoyaltyOwnerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AuthProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("auth_provider_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin");

                    b.Property<Guid>("LoyaltyOwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loyalty_owner_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__loyalty___3213E83FCA9F25E5");

                    b.HasIndex(new[] { "LoyaltyOwnerId" }, "idx_loyalty_owner_user_owner_id");

                    b.ToTable("loyalty_owner_user", (string)null);
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.LoyaltyProgramme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LoyaltyOwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loyalty_owner_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__loyalty___3213E83F9D47D4D7");

                    b.HasIndex(new[] { "LoyaltyOwnerId" }, "idx_loyalty_programme_owner_id");

                    b.ToTable("loyalty_programme", (string)null);
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("CostPoints")
                        .HasColumnType("int")
                        .HasColumnName("cost_points");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("LoyaltyProgrammeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loyalty_programme_id");

                    b.Property<int?>("MaxScans")
                        .HasColumnType("int")
                        .HasColumnName("max_scans");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reward_type");

                    b.HasKey("Id")
                        .HasName("PK__reward__3213E83F40482097");

                    b.HasIndex(new[] { "LoyaltyProgrammeId" }, "idx_reward_programme_id");

                    b.ToTable("reward", (string)null);
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.RewardRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("LoyaltyOwnerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loyalty_owner_user_id");

                    b.Property<Guid>("LoyaltyProgrammeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loyalty_programme_id");

                    b.Property<DateTime>("RedeemedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("redeemed_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reward_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__reward_r__3213E83FC9ADA235");

                    b.HasIndex("LoyaltyOwnerUserId");

                    b.HasIndex("RewardId");

                    b.HasIndex(new[] { "LoyaltyProgrammeId" }, "idx_reward_redemption_programme_id");

                    b.HasIndex(new[] { "UserId" }, "idx_reward_redemption_user_id");

                    b.ToTable("reward_redemption", (string)null);
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.ScanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("LoyaltyOwnerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loyalty_owner_user_id");

                    b.Property<Guid>("LoyaltyProgrammeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loyalty_programme_id");

                    b.Property<int>("PointsChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("points_change");

                    b.Property<DateTime>("ScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("scanned_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__scan_eve__3213E83F45201827");

                    b.HasIndex("LoyaltyOwnerUserId");

                    b.HasIndex(new[] { "LoyaltyProgrammeId" }, "idx_scan_event_programme_id");

                    b.HasIndex(new[] { "UserId" }, "idx_scan_event_user_id");

                    b.ToTable("scan_event", (string)null);
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AuthProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("auth_provider_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("QrCodeValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("qr_code_value");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83F4461F44E");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164CB0A1AE0")
                        .IsUnique();

                    b.HasIndex(new[] { "AuthProviderId" }, "UQ__users__C82CBBE99CDF45A3")
                        .IsUnique();

                    b.HasIndex(new[] { "QrCodeValue" }, "UQ__users__C8EB4B8153934E5A")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.UserBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("Balance")
                        .HasColumnType("int")
                        .HasColumnName("balance");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("LoyaltyProgrammeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loyalty_programme_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__user_bal__3213E83F23104F90");

                    b.HasIndex(new[] { "LoyaltyProgrammeId" }, "idx_user_balance_programme_id");

                    b.HasIndex(new[] { "UserId" }, "idx_user_balance_user_id");

                    b.HasIndex(new[] { "UserId", "LoyaltyProgrammeId" }, "uq_user_balance")
                        .IsUnique();

                    b.ToTable("user_balance", (string)null);
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.LoyaltyOwnerUser", b =>
                {
                    b.HasOne("TapForPerksAPI.Entities.LoyaltyOwner", "LoyaltyOwner")
                        .WithMany("LoyaltyOwnerUsers")
                        .HasForeignKey("LoyaltyOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loyalty_owner_user_owner");

                    b.Navigation("LoyaltyOwner");
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.LoyaltyProgramme", b =>
                {
                    b.HasOne("TapForPerksAPI.Entities.LoyaltyOwner", "LoyaltyOwner")
                        .WithMany("LoyaltyProgrammes")
                        .HasForeignKey("LoyaltyOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loyalty_programme_owner");

                    b.Navigation("LoyaltyOwner");
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.Reward", b =>
                {
                    b.HasOne("TapForPerksAPI.Entities.LoyaltyProgramme", "LoyaltyProgramme")
                        .WithMany("Rewards")
                        .HasForeignKey("LoyaltyProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reward_programme");

                    b.Navigation("LoyaltyProgramme");
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.RewardRedemption", b =>
                {
                    b.HasOne("TapForPerksAPI.Entities.LoyaltyOwnerUser", "LoyaltyOwnerUser")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("LoyaltyOwnerUserId")
                        .HasConstraintName("fk_reward_redemption_owner_user");

                    b.HasOne("TapForPerksAPI.Entities.LoyaltyProgramme", "LoyaltyProgramme")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("LoyaltyProgrammeId")
                        .IsRequired()
                        .HasConstraintName("fk_reward_redemption_programme");

                    b.HasOne("TapForPerksAPI.Entities.Reward", "Reward")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reward_redemption_reward");

                    b.HasOne("TapForPerksAPI.Entities.User", "User")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reward_redemption_user");

                    b.Navigation("LoyaltyOwnerUser");

                    b.Navigation("LoyaltyProgramme");

                    b.Navigation("Reward");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.ScanEvent", b =>
                {
                    b.HasOne("TapForPerksAPI.Entities.LoyaltyOwnerUser", "LoyaltyOwnerUser")
                        .WithMany("ScanEvents")
                        .HasForeignKey("LoyaltyOwnerUserId")
                        .HasConstraintName("fk_scan_event_owner_user");

                    b.HasOne("TapForPerksAPI.Entities.LoyaltyProgramme", "LoyaltyProgramme")
                        .WithMany("ScanEvents")
                        .HasForeignKey("LoyaltyProgrammeId")
                        .IsRequired()
                        .HasConstraintName("fk_scan_event_programme");

                    b.HasOne("TapForPerksAPI.Entities.User", "User")
                        .WithMany("ScanEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_event_user");

                    b.Navigation("LoyaltyOwnerUser");

                    b.Navigation("LoyaltyProgramme");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.UserBalance", b =>
                {
                    b.HasOne("TapForPerksAPI.Entities.LoyaltyProgramme", "LoyaltyProgramme")
                        .WithMany("UserBalances")
                        .HasForeignKey("LoyaltyProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_balance_programme");

                    b.HasOne("TapForPerksAPI.Entities.User", "User")
                        .WithMany("UserBalances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_balance_user");

                    b.Navigation("LoyaltyProgramme");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.LoyaltyOwner", b =>
                {
                    b.Navigation("LoyaltyOwnerUsers");

                    b.Navigation("LoyaltyProgrammes");
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.LoyaltyOwnerUser", b =>
                {
                    b.Navigation("RewardRedemptions");

                    b.Navigation("ScanEvents");
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.LoyaltyProgramme", b =>
                {
                    b.Navigation("RewardRedemptions");

                    b.Navigation("Rewards");

                    b.Navigation("ScanEvents");

                    b.Navigation("UserBalances");
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.Reward", b =>
                {
                    b.Navigation("RewardRedemptions");
                });

            modelBuilder.Entity("TapForPerksAPI.Entities.User", b =>
                {
                    b.Navigation("RewardRedemptions");

                    b.Navigation("ScanEvents");

                    b.Navigation("UserBalances");
                });
#pragma warning restore 612, 618
        }
    }
}
