// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaveForPerksAPI.DbContexts;

#nullable disable

namespace SaveForPerksAPI.Migrations
{
    [DbContext(typeof(SaveForPerksContext))]
    [Migration("20260209164904_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaveForPerksAPI.Entities.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("business", (string)null);
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.BusinessCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("business_category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageUrl = "/images/categories/cafe.png",
                            Name = "Cafe"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ImageUrl = "/images/categories/coffee-shop.png",
                            Name = "Coffee Shop"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ImageUrl = "/images/categories/restaurant.png",
                            Name = "Restaurant"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ImageUrl = "/images/categories/bakery.png",
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ImageUrl = "/images/categories/bar-pub.png",
                            Name = "Bar & Pub"
                        });
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.BusinessUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AuthProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("auth_provider_id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("is_admin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AuthProviderId")
                        .IsUnique();

                    b.HasIndex("BusinessId");

                    b.ToTable("business_user", (string)null);
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AuthProviderId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("auth_provider_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("QrCodeValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("qr_code_value");

                    b.HasKey("Id");

                    b.HasIndex("AuthProviderId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("QrCodeValue")
                        .IsUnique();

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.CustomerBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("Balance")
                        .HasColumnType("int")
                        .HasColumnName("balance");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reward_id");

                    b.HasKey("Id");

                    b.HasIndex("RewardId");

                    b.HasIndex("CustomerId", "RewardId")
                        .IsUnique();

                    b.ToTable("customer_balance", (string)null);
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_id");

                    b.Property<int>("CostPoints")
                        .HasColumnType("int")
                        .HasColumnName("cost_points");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reward_type");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("reward", (string)null);
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.RewardRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("BusinessUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_user_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("RedeemedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("redeemed_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reward_id");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RewardId");

                    b.ToTable("reward_redemption", (string)null);
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.ScanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("BusinessUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_user_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<int>("PointsChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("points_change");

                    b.Property<string>("QrCodeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("qr_code_value");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reward_id");

                    b.Property<DateTime>("ScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("scanned_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RewardId");

                    b.ToTable("scan_event", (string)null);
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.Business", b =>
                {
                    b.HasOne("SaveForPerksAPI.Entities.BusinessCategory", "Category")
                        .WithMany("Businesses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.BusinessUser", b =>
                {
                    b.HasOne("SaveForPerksAPI.Entities.Business", "Business")
                        .WithMany("BusinessUsers")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.CustomerBalance", b =>
                {
                    b.HasOne("SaveForPerksAPI.Entities.Customer", "Customer")
                        .WithMany("CustomerBalances")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaveForPerksAPI.Entities.Reward", "Reward")
                        .WithMany("CustomerBalances")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.Reward", b =>
                {
                    b.HasOne("SaveForPerksAPI.Entities.Business", "Business")
                        .WithMany("Rewards")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.RewardRedemption", b =>
                {
                    b.HasOne("SaveForPerksAPI.Entities.BusinessUser", "BusinessUser")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("BusinessUserId");

                    b.HasOne("SaveForPerksAPI.Entities.Customer", "Customer")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaveForPerksAPI.Entities.Reward", "Reward")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("RewardId")
                        .IsRequired();

                    b.Navigation("BusinessUser");

                    b.Navigation("Customer");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.ScanEvent", b =>
                {
                    b.HasOne("SaveForPerksAPI.Entities.BusinessUser", "BusinessUser")
                        .WithMany("ScanEvents")
                        .HasForeignKey("BusinessUserId");

                    b.HasOne("SaveForPerksAPI.Entities.Customer", "Customer")
                        .WithMany("ScanEvents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaveForPerksAPI.Entities.Reward", "Reward")
                        .WithMany("ScanEvents")
                        .HasForeignKey("RewardId")
                        .IsRequired();

                    b.Navigation("BusinessUser");

                    b.Navigation("Customer");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.Business", b =>
                {
                    b.Navigation("BusinessUsers");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.BusinessCategory", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.BusinessUser", b =>
                {
                    b.Navigation("RewardRedemptions");

                    b.Navigation("ScanEvents");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.Customer", b =>
                {
                    b.Navigation("CustomerBalances");

                    b.Navigation("RewardRedemptions");

                    b.Navigation("ScanEvents");
                });

            modelBuilder.Entity("SaveForPerksAPI.Entities.Reward", b =>
                {
                    b.Navigation("CustomerBalances");

                    b.Navigation("RewardRedemptions");

                    b.Navigation("ScanEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
